// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/v1/Todo.proto

package Todo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Todo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Todo) Reset()         { *m = Todo{} }
func (m *Todo) String() string { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()    {}
func (*Todo) Descriptor() ([]byte, []int) {
	return fileDescriptor_68316bae589d77a5, []int{0}
}

func (m *Todo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Todo.Unmarshal(m, b)
}
func (m *Todo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Todo.Marshal(b, m, deterministic)
}
func (m *Todo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Todo.Merge(m, src)
}
func (m *Todo) XXX_Size() int {
	return xxx_messageInfo_Todo.Size(m)
}
func (m *Todo) XXX_DiscardUnknown() {
	xxx_messageInfo_Todo.DiscardUnknown(m)
}

var xxx_messageInfo_Todo proto.InternalMessageInfo

func (m *Todo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Todo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Todo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type GetTodoResponse struct {
	Todo                 []*Todo  `protobuf:"bytes,1,rep,name=todo,proto3" json:"todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTodoResponse) Reset()         { *m = GetTodoResponse{} }
func (m *GetTodoResponse) String() string { return proto.CompactTextString(m) }
func (*GetTodoResponse) ProtoMessage()    {}
func (*GetTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68316bae589d77a5, []int{1}
}

func (m *GetTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTodoResponse.Unmarshal(m, b)
}
func (m *GetTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTodoResponse.Marshal(b, m, deterministic)
}
func (m *GetTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTodoResponse.Merge(m, src)
}
func (m *GetTodoResponse) XXX_Size() int {
	return xxx_messageInfo_GetTodoResponse.Size(m)
}
func (m *GetTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTodoResponse proto.InternalMessageInfo

func (m *GetTodoResponse) GetTodo() []*Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

func init() {
	proto.RegisterType((*Todo)(nil), "Todo")
	proto.RegisterType((*GetTodoResponse)(nil), "GetTodoResponse")
}

func init() { proto.RegisterFile("api/proto/v1/Todo.proto", fileDescriptor_68316bae589d77a5) }

var fileDescriptor_68316bae589d77a5 = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8e, 0xcd, 0x4a, 0xc4, 0x30,
	0x14, 0x85, 0xe9, 0x9f, 0xe2, 0x2d, 0xa8, 0x04, 0xd1, 0xd8, 0x55, 0xe9, 0xaa, 0x0b, 0x49, 0xb0,
	0x7d, 0x03, 0x41, 0xdc, 0xb9, 0xa8, 0xbe, 0xc0, 0xb4, 0xb9, 0x53, 0x02, 0x9d, 0xde, 0xd0, 0x66,
	0x0a, 0xf3, 0xf6, 0x43, 0x92, 0x59, 0x0c, 0xb3, 0x3c, 0xdf, 0x3d, 0xf7, 0xf0, 0xc1, 0xdb, 0xce,
	0x68, 0x69, 0x16, 0xb2, 0x24, 0xb7, 0x4f, 0xf9, 0x4f, 0x8a, 0x84, 0x4f, 0x05, 0x1b, 0x89, 0xc6,
	0x09, 0x25, 0x1e, 0x8c, 0x3d, 0x05, 0x56, 0xfd, 0x42, 0xea, 0x1a, 0xec, 0x11, 0x62, 0xad, 0x78,
	0x54, 0x46, 0xf5, 0x43, 0x17, 0x6b, 0xc5, 0x5e, 0x20, 0xb3, 0xda, 0x4e, 0xc8, 0x63, 0x8f, 0x42,
	0x60, 0x25, 0xe4, 0x0a, 0xd7, 0x61, 0xd1, 0xc6, 0x6a, 0x9a, 0x79, 0xe2, 0x6f, 0xd7, 0xa8, 0xfa,
	0x80, 0xa7, 0x1f, 0xb4, 0x6e, 0xb2, 0xc3, 0xd5, 0xd0, 0xbc, 0x22, 0x7b, 0x87, 0xd4, 0x92, 0x22,
	0x1e, 0x95, 0x49, 0x9d, 0x37, 0x99, 0xf0, 0x47, 0x8f, 0x9a, 0x2f, 0xc8, 0x5d, 0xfa, 0xc3, 0x65,
	0xd3, 0x03, 0xb2, 0x16, 0xee, 0x2f, 0xcf, 0xec, 0x55, 0x04, 0xd9, 0xa0, 0xd9, 0x1f, 0xf7, 0xe2,
	0xdb, 0x59, 0x17, 0xcf, 0xe2, 0x66, 0xbe, 0xbf, 0xf3, 0x8d, 0xf6, 0x1c, 0x00, 0x00, 0xff, 0xff,
	0xb9, 0xbe, 0xbf, 0xef, 0xf7, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TodoServiceClient is the client API for TodoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodoServiceClient interface {
	GetTodo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetTodoResponse, error)
}

type todoServiceClient struct {
	cc *grpc.ClientConn
}

func NewTodoServiceClient(cc *grpc.ClientConn) TodoServiceClient {
	return &todoServiceClient{cc}
}

func (c *todoServiceClient) GetTodo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetTodoResponse, error) {
	out := new(GetTodoResponse)
	err := c.cc.Invoke(ctx, "/TodoService/GetTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoServiceServer is the server API for TodoService service.
type TodoServiceServer interface {
	GetTodo(context.Context, *empty.Empty) (*GetTodoResponse, error)
}

func RegisterTodoServiceServer(s *grpc.Server, srv TodoServiceServer) {
	s.RegisterService(&_TodoService_serviceDesc, srv)
}

func _TodoService_GetTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).GetTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TodoService/GetTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).GetTodo(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _TodoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TodoService",
	HandlerType: (*TodoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTodo",
			Handler:    _TodoService_GetTodo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/Todo.proto",
}
